"""한국 공항 공공 API Python 클라이언트."""

from pykrtour import Address, PlaceCoordinate

from pykrairport.airports import (
    AIRPORTS,
    IIAC_AIRPORTS,
    KAC_AIRPORTS,
    SUPPORTED_AIRPORT_CODES,
    get_airport,
    get_airport_or_none,
    list_airports,
    nearest_airport,
)
from pykrairport.client import KrairportClient
from pykrairport.enums import (
    Airport,
    AirportType,
    ApiLanguage,
    CoordinateDatum,
    Direction,
    Provider,
    ScheduleType,
)
from pykrairport.exceptions import (
    KrairportAuthError,
    KrairportError,
    KrairportNetworkError,
    KrairportParseError,
    KrairportRateLimitError,
    KrairportRequestError,
    KrairportServerError,
    UnsupportedAirportError,
)
from pykrairport.models import (
    AircraftAssignment,
    AirportCode,
    AirportFacility,
    AirportMetadata,
    ArrivalCongestion,
    BusRoute,
    Flight,
    FlightSchedule,
    KrairportModel,
    ParkingAreaStatus,
    ParkingFee,
    PassengerForecast,
    ServiceDestination,
    TaxiStatus,
    WorldWeather,
)
from pykrairport.types import (
    AirportCodeLike,
    AirportCodeText,
    CoordinateTuple,
    DirectionCode,
    DirectionLike,
    GeoJsonPosition,
    ProviderCode,
    ProviderLike,
    RawRecord,
)

__version__ = "0.1.0"

__all__ = [
    "AIRPORTS",
    "Address",
    "AircraftAssignment",
    "Airport",
    "AirportCode",
    "AirportCodeLike",
    "AirportCodeText",
    "AirportFacility",
    "AirportMetadata",
    "AirportType",
    "ApiLanguage",
    "ArrivalCongestion",
    "BusRoute",
    "CoordinateDatum",
    "CoordinateTuple",
    "Direction",
    "DirectionCode",
    "DirectionLike",
    "FlightSchedule",
    "Flight",
    "GeoJsonPosition",
    "IIAC_AIRPORTS",
    "KAC_AIRPORTS",
    "KrairportAuthError",
    "KrairportClient",
    "KrairportError",
    "KrairportModel",
    "KrairportNetworkError",
    "KrairportParseError",
    "KrairportRateLimitError",
    "KrairportRequestError",
    "KrairportServerError",
    "ParkingAreaStatus",
    "ParkingFee",
    "PassengerForecast",
    "PlaceCoordinate",
    "Provider",
    "ProviderCode",
    "ProviderLike",
    "RawRecord",
    "SUPPORTED_AIRPORT_CODES",
    "ScheduleType",
    "ServiceDestination",
    "TaxiStatus",
    "UnsupportedAirportError",
    "WorldWeather",
    "__version__",
    "get_airport",
    "get_airport_or_none",
    "list_airports",
    "nearest_airport",
]
